import matplotlib.pyplot as plt
from sklearn.manifold import TSNE


# Texts from the municipal corpus
corpus = [
    "The City Hall renovation project is moving forward.",
    "A new school will be inaugurated next month.",
    "The works on the main road are finished.",
    "The municipal library is organizing an exhibition.",
    "A sustainable development plan has been adopted."
]


# 1. Getting the embeddings with Sentence-BERT
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
sbert_embeddings = sbert_model.encode(corpus)


# Dimensionality reduction for the visualization with t-SNE
sbert_tsne = TSNE(n_components=2, random_state=0)
sbert_embeddings_2d = sbert_tsne.fit_transform(sbert_embeddings)


# Visualization of the Sentence-BERT embeddings
plt.figure(figsize=(8, 6))
plt.scatter(sbert_embeddings_2d[:, 0], sbert_embeddings_2d[:, 1], color='blue')
for i, txt in enumerate(corpus):
    plt.annotate(txt, (sbert_embeddings_2d[i, 0], sbert_embeddings_2d[i, 1]), fontsize=9)
plt.title("Visualization of the embeddings with Sentence-BERT")
plt.xlabel("Dimension 1")
plt.ylabel("Dimension 2")
plt.show()


### Visualization with Mistral embeddings
Here is how to generate the embeddings and visualize them with Mistral:


from mistral.embedding import EmbeddingClient


# Initializing the Mistral client
client = EmbeddingClient(api_key='YOUR_API_KEY')


# Getting the embeddings with Mistral
mistral_embeddings = [client.get_embedding(text) for text in corpus]


# Dimensionality reduction for the Mistral embeddings
mistral_tsne = TSNE(n_components=2, random_state=0).fit_transform(mistral_embeddings)


# Visualization of the Mistral embeddings
plt.figure(figsize=(8, 6))
plt.scatter(mistral_tsne[:, 0], mistral_tsne[:, 1], color='green')
for i, txt in enumerate(corpus):
    plt.annotate(txt, (mistral_tsne[i, 0], mistral_tsne[i, 1]), fontsize=9)
plt.title("Visualization of the embeddings with Mistral")
plt.xlabel("Dimension 1")
plt.ylabel("Dimension 2")
plt.show()


### Comparison with fastText
We can compare the embeddings generated by SBERT and Mistral with those produced by fastText.


import fasttext.util
import numpy as np
import seaborn as sns


# Downloading and loading the fastText model
fasttext.util.download_model('en', if_exists='ignore')  # English model
ft = fasttext.load_model('cc.en.300.bin')


# Getting the fastText embeddings
fasttext_embeddings = [ft.get_sentence_vector(text) for text in corpus]


# Dimensionality reduction for the fastText embeddings
fasttext_tsne = TSNE(n_components=2, random_state=0).fit_transform(np.array(fasttext_embeddings))


# Visualization of the fastText embeddings
plt.figure(figsize=(8, 6))
ax = sns.scatterplot(x=fasttext_tsne[:, 0], y=fasttext_tsne[:, 1], hue=corpus, palette="deep")
sns.move_legend(ax, 'upper left', bbox_to_anchor=(1, 1))
plt.title("Visualization of the embeddings with fastText")
plt.xlabel("Dimension 1")
plt.ylabel("Dimension 2")
plt.show()
